import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Typography } from "@mui/material";
import Head from 'next/head'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head><meta name="viewport" content="initial-scale=1, width=device-width" />

</Head>
      <body className={inter.className}>
        {" "}
        <nav>
          <Link href="/about"><Typography>about me</Typography></Link>
          <Link href="/projects"><Typography>project</Typography></Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
